version: 2
jobs: 
  build:
    docker:
      - image: circleci/node:11.0.0
    steps: 
      - checkout
      - run: npm i
      - run: npm run build
      - run: cd dist
      - run: npm login --token 3b6d98e9-4647-430d-95f4-bc69ca66d9d0
      - run: npm publish
workflows:
  version: 2
  build_and_publish:
    jobs:
      - build:
         filters:
            branches:
              only:
                - master  