version: 2
jobs: 
  build:
    docker:
      - image: circleci/node:11.0.0
    steps: 
      - checkout
      - run: npm i
      - run: npm run build
      - run: cd dist
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=3b6d98e9-4647-430d-95f4-bc69ca66d9d0" > ~/repo/.npmrc
      - run: npm publish
workflows:
  version: 2
  build_and_publish:
    jobs:
      - build:
         filters:
            branches:
              only:
                - master  